# -*- coding: utf-8 -*-
"""consulta_padrones_ARBA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEuf597eye4p9Avlw6Dn-ScTxIdCa3C7
"""

import streamlit as st
import pandas as pd
from datetime import datetime

#Confeccionamos el padron
columnas = ["Fecha_Consulta", "Fecha_desde", "Fecha_hasta", "CUIT", "A0", "A1", "A2", "Alicuota", "A3", "A4"]
padron1 = pd.read_csv("parte_1.txt", sep=";", header=None, names=columnas, dtype=str)
padron2 = pd.read_csv("parte_2.txt", sep=";", header=None, names=columnas, dtype=str)
padron3 = pd.read_csv("parte_3.txt", sep=";", header=None, names=columnas, dtype=str)
padron4 = pd.read_csv("parte_4.txt", sep=";", header=None, names=columnas, dtype=str)
padron5 = pd.read_csv("parte_5.txt", sep=";", header=None, names=columnas, dtype=str)
padron6 = pd.read_csv("parte_6.txt", sep=";", header=None, names=columnas, dtype=str)
padron7 = pd.read_csv("parte_7.txt", sep=";", header=None, names=columnas, dtype=str)
padron8 = pd.read_csv("parte_8.txt", sep=";", header=None, names=columnas, dtype=str)
padron9 = pd.read_csv("parte_9.txt", sep=";", header=None, names=columnas, dtype=str)
padron10 = pd.read_csv("parte_10.txt", sep=";", header=None, names=columnas, dtype=str)

padrones_unidos = pd.concat(
    [padron1, padron2, padron3, padron4, padron5,
     padron6, padron7, padron8, padron9, padron10],
    ignore_index=True
)
padrones_unidos.head()

# Cargar padrón desde archivo txt
@st.cache_data
def cargar_padron():
    padrones_unidos["CUIT"] = padrones_unidos["CUIT"].str.strip()
    padrones_unidos["Alicuota"] = padrones_unidos["Alicuota"].str.strip()
    #return df[["CUIT", "Alicuota"]].drop_duplicates()

padrones_ret = cargar_padron()

st.title("Consulta de Alícuota por CUIT")

# -------------------------
# 🔹 CONSULTA INDIVIDUAL
# -------------------------
st.subheader("🔎 Consulta Individual")

cuit_input = st.text_input("Ingresá un CUIT para consultar:")

if st.button("Consultar"):
    cuit_input = cuit_input.strip()
    if not cuit_input:
        st.warning("Ingresá un CUIT válido.")
    else:
        resultado = padrones_ret[padrones_ret["CUIT"] == cuit_input]
        if not resultado.empty:
            st.success("Resultado encontrado:")
            st.dataframe(resultado)

            nombre_archivo = f"consulta_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
            resultado.to_csv(nombre_archivo, index=False)
            with open(nombre_archivo, "rb") as f:
                st.download_button("📥 Descargar resultado", f, file_name=nombre_archivo)
        else:
            st.error("CUIT no encontrado.")

# -------------------------
# 📂 CONSULTA POR ARCHIVO
# -------------------------
st.markdown("---")
st.subheader("📂 Consulta por Lote (archivo CSV)")

archivo = st.file_uploader("Subí un archivo .csv con columna 'CUIT'", type=["csv"])

if archivo is not None:
    try:
        cuit_consulta = pd.read_csv(archivo, dtype=str)
        if "CUIT" not in cuit_consulta.columns:
            st.error("El archivo debe tener una columna llamada 'CUIT'.")
        else:
            cuit_consulta["CUIT"] = cuit_consulta["CUIT"].str.strip()
            resultado_lote = pd.merge(cuit_consulta[["CUIT"]], padrones_ret, on="CUIT", how="left")
            st.success("Consulta por lote realizada:")
            st.dataframe(resultado_lote)

            nombre_archivo_lote = f"resultado_lote_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
            resultado_lote.to_csv(nombre_archivo_lote, index=False)

            with open(nombre_archivo_lote, "rb") as f:
                st.download_button("⬇️ Descargar archivo resultado", f, file_name=nombre_archivo_lote)
    except Exception as e:
        st.error(f"Ocurrió un error al procesar el archivo: {e}")